maximized = false
transparency = 0.5
neovide_scroll_animation_length = 0.2

[font]
normal = {family="Iosevka Paper Condensed", style = "Condensed"}

# normal = {family="Zed Mono", style = "Extended"}

# normal = { family = "Victor Mono", style = "Medium"}
# italic = { family = "Victor Mono", style = "Medium Italic"}
# bold = "Victor Mono"

# normal = { family = "Monaspace Argon"}
# italic = { family = "Monaspace Radon" }
# bold = { family = "Monaspace Krypton" }

size = 13

[font.features]
