#!/usr/bin/bash

mpv --no-cache --untimed --no-demuxer-thread --video-sync=audio --vf=hflip,lavfi-crop=w=400:h=300:x=120:y=20 --vd-lavc-threads=1 --no-osc --no-input-default-bindings --autofit=25% /dev/video0
