#!/bin/bash

DIR=$HOME/Pictures/wallpapers
PICS=($(ls ${DIR} | grep -e ".jpg$" -e ".jpeg$" -e ".png$" -e ".gif$"))
RANDOMPICS=$DIR/${PICS[$RANDOM % ${#PICS[@]}]}

change_bg() {
  hyprctl hyprpaper preload "$RANDOMPICS"
  hyprctl hyprpaper wallpaper "eDP-1,${RANDOMPICS}"
  hyprctl hyprpaper unload all
}

change_bg
