#!/bin/bash

DIR=$HOME/Pictures/wallpapers
PICS=($(ls ${DIR} | grep -e ".jpg$" -e ".jpeg$" -e ".png$" -e ".gif$"))
RANDOMPICS=$DIR/${PICS[$RANDOM % ${#PICS[@]}]}

change_bg() {
  notify-send -u normal "Changing wallpaper to $RANDOMPICS"
  hyprctl hyprpaper wallpaper "eDP-1,${RANDOMPICS}"
}

change_bg
