#!/bin/bash

# WALLPAPERS PATH
DIR=~/Pictures/wallpapers

# Transition config (type swww img --help for more settings
FPS=30
TYPE="simple"
DURATION=1

# wofi window config (in %)
WIDTH=20
HEIGHT=30

PICS=($(ls ${DIR} | grep -e ".jpg$" -e ".jpeg$" -e ".png$" -e ".gif$"))

RANDOM_PIC=${PICS[$RANDOM % ${#PICS[@]}]}
RANDOM_PIC_NAME="${#PICS[@]}. random"

# WOFI STYLES
CONFIG="$HOME/.config/hypr/wofifull/config"
COLORS="$HOME/.config/hypr/wofifull/colors"

## Wofi Command
wofi_command="wofi --show dmenu \
			--prompt choose...
			--conf "$CONFIG" \
			--width=$WIDTH% --height=$HEIGHT% \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--matching=fuzzy"

menu() {
  # Here we are looping in the PICS array that is composed of all images in the $DIR
  # folder
  for i in "${!PICS[@]}"; do
    # keeping the .gif to make sue you know it is animated
    if [[ -z $(echo ${PICS[$i]} | grep .gif$) ]]; then
      printf "$i. $(echo ${PICS[$i]} | cut -d. -f1)\n" # n°. <name_of_file_without_identifier>
    else
      printf "$i. ${PICS[$i]}\n"
    fi
  done

  echo "$RANDOM_PIC_NAME"
}

main() {
  choice=$(menu | ${wofi_command})

  # no choice case
  if [[ -z $choice ]]; then return; fi

  notify-send Selected "$choice"

  pic_index=$(echo $choice | cut -d. -f1)
  monitor=$(hyprctl monitors | grep Monitor | awk '{print $2}')

  hyprctl hyprpaper unload all
  hyprctl hyprpaper preload "$DIR/${PICS[$pic_index]}"
  hyprctl hyprpaper wallpaper "$monitor, $DIR/${PICS[$pic_index]}"
}

# Check if wofi is already running
if pidof wofi >/dev/null; then
  killall wofi
  exit 0
else
  main
fi

# Uncomment to launch something if a choice was made
# if [[ -n "$choice" ]]; then
# Restart Waybar
# fi
