#!/bin/bash

# WALLPAPERS PATH
DIR=~/Pictures/wallpapers

PICS=($(ls ${DIR} | grep -e ".jpg$" -e ".jpeg$" -e ".png$" -e ".gif$"))

RANDOM_PIC=${PICS[$RANDOM % ${#PICS[@]}]}
RANDOM_PIC_NAME="${#PICS[@]}. random"

# WOFI STYLES
CONFIG="$HOME/.config/hypr/wofifull/config"
COLORS="$HOME/.config/hypr/wofifull/colors"

## Wofi Command
wofi_command="fuzzel -d \
			--prompt Choose..."

menu() {
  # Here we are looping in the PICS array that is composed of all images in the $DIR
  # folder
  for i in "${!PICS[@]}"; do
    # keeping the .gif to make sue you know it is animated
    if [[ -z $(echo ${PICS[$i]} | grep .gif$) ]]; then
      printf "$i. $(echo ${PICS[$i]} | cut -d. -f1)\n" # n°. <name_of_file_without_identifier>
    else
      printf "$i. ${PICS[$i]}\n"
    fi
  done

  echo "$RANDOM_PIC_NAME"
}

main() {
  choice=$(menu | ${wofi_command})

  # no choice case
  if [[ -z $choice ]]; then return; fi

  notify-send Selected "$choice"

  pic_index=$(echo $choice | cut -d. -f1)
  monitor=$(hyprctl monitors all -j | jq -r '.[] | select(.focused==true) | .name')

  hyprctl hyprpaper unload all
  hyprctl hyprpaper preload "$DIR/${PICS[$pic_index]}"
  hyprctl hyprpaper wallpaper "$monitor, $DIR/${PICS[$pic_index]}"
}

if pidof fuzzel >/dev/null; then
  killall fuzzel
  exit 0
else
  main
fi
