#!/bin/bash

## Files
CONFIG="$HOME/.config/hypr/wofifull/config"
STYLE="$HOME/.config/hypr/wofifull/style.css"
COLORS="$HOME/.config/hypr/wofifull/colors"
iDIR="$HOME/.config/hypr/mako/icons"

## Wofi Command
wofi_command="wofi --show dmenu \
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=350 --height=380 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

notification() {
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/music.png" "Now Playing: Online Music"
}

menu() {
  printf "1. Lofi Girl\n"
  printf "2. Anime songs\n"
  printf "3. Box Lofi\n"
  printf "4. Top Music 2023\n"
  printf "5. Youtube Global Top 100\n"
  printf "6. SmoothChill\n"
  printf "7. Relaxing Music\n"
  printf "8. Youtube Remix\n"
}

main() {
  choice=$(menu | ${wofi_command} | cut -d. -f1)
  case $choice in
  1)
    notification
    mpv --input-ipc-server=/tmp/mpvsocket "https://play.streamafrica.net/lofiradio"
    return
    ;;
  2)
    notification
    mpv --input-ipc-server=/tmp/mpvsocket --shuffle --vid=no "https://www.youtube.com/playlist?list=PL8lZieNFgOdmrNGTqwjqYJpJ_2nw_O_M2"
    return
    ;;
  3)
    notification
    mpv --input-ipc-server=/tmp/mpvsocket "http://stream.zeno.fm/f3wvbbqmdg8uv"
    return
    ;;
  4)
    notification
    mpv --input-ipc-server=/tmp/mpvsocket --shuffle --vid=no --input-ipc-server=/tmp/mpvsocket "https://youtube.com/playlist?list=PL6k9a6aYB2zk0qSbXR-ZEiwqgdHymsRtQ"
    return
    ;;
  5)
    notification
    mpv --input-ipc-server=/tmp/mpvsocket --shuffle --vid=no --input-ipc-server=/tmp/mpvsocket "https://youtube.com/playlist?list=PL4fGSI1pDJn5kI81J1fYWK5eZRl1zJ5kM"
    return
    ;;
  6)
    notification
    mpv "https://media-ssl.musicradio.com/SmoothChill"
    return
    ;;
  7)
    notification
    mpv --input-ipc-server=/tmp/mpvsocket --shuffle --vid=no "https://youtube.com/playlist?list=PLMIbmfP_9vb8BCxRoraJpoo4q1yMFg4CE"
    return
    ;;
  8)
    notification
    mpv --input-ipc-server=/tmp/mpvsocket --shuffle --vid=no "https://youtube.com/playlist?list=PLeqTkIUlrZXlSNn3tcXAa-zbo95j0iN-0"
    return
    ;;
  esac
}

pkill -f http && \
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/music.png" "Online Music stopped" || \
  (pidof wofi && pkill wofi || main)
