[opener]
# play = [
#   { run = 'mpv %s', orphan = true, for = "unix" },
#   { run = '"C:\Program Files\mpv.exe" %s', orphan = true, for = "windows" },
# ]
edit = [
  { run = '${EDITOR:-nvim} %s', block = true, for = "unix" },
  { run = "%EDITOR% %s", block = true, for = "windows" },
]
pdf = [
  { run = 'sioyek --new-instance %s', desc = "Open in Sioyek", for = "unix" },
]

[open]
prepend_rules = [
  { mime = "application/pdf", use = [ "pdf", "open", "reveal" ] },
]

[mgr]
linemode = "size"
